### ISSUE TITLE
Add Triton Information to README.md

### ISSUE THREAD

**Issue by nstarke** [Sentinel-One/efi_fuzz#10]
`taint/tracker.py` has an import for `Triton` - it would be helpful to have information about where Triton can be installed from in the `README.md`.  

I suggest adding this link to the `README.md`: [https://triton.quarkslab.com/documentation/doxygen/#install_sec](https://triton.quarkslab.com/documentation/doxygen/#install_sec)

If its acceptable to you I can create a pull request with this change?  Thanks.

**Comment by assafcarlsbad** [comment]
Sure, a pull request will be much welcomed.

**Comment by assafcarlsbad** [comment]
Thanks for your contribution!
