### ISSUE TITLE
scripts/prepare_nvram.py generates pickle file that is only 5-9 bytes in size

### ISSUE THREAD

**Issue by nstarke** [Sentinel-One/efi_fuzz#9]
Hello,

I've tried running several BIOS images through the `scripts/prepare_nvram.py` script and the end result is always a pickle file that is 5-9 bytes in size.  This leads me to believe the script is not finding the UEFI variables contained within the BIOS image.  I tried debugging this myself to see what "type" of UEFI object is found at the bottom of the nested looping structure in the code, and I am consistently seeing that it is `FirmwareFileSystemSection` and not `NVarVariableStore`. 

When I load the BIOS images into UEFITool, I don't see any nodes labeled `NVarVariableStore` either, though this might just be a presentation difference between UEFITool and efi_fuzz.

If you need a BIOS image to test against I believe I can provide one.  Thanks for your help!

**Comment by assafcarlsbad** [comment]
Hi,
Thanks for reporting this issue!

It's quite difficult to debug the problem from the description alone, so a BIOS image can definitely help here.
You can send it to me at carlsbad@sentinelone.com if you don't want it to be public.

**Comment by nstarke** [comment]
Hi,
Just to follow up on this, I sent an email.  I'll look forward to continuing the conversation privately.  Thanks!

**Comment by assafcarlsbad** [comment]
New scripts are now merged to `master`.
